use anyhow::Result;
use std::path::Path;

/// Generate a nemo.toml configuration file by scanning the monorepo.
pub fn run(force: bool) -> Result<()> {
    let nemo_toml = Path::new("nemo.toml");

    if nemo_toml.exists() && !force {
        anyhow::bail!("nemo.toml already exists. Use --force to overwrite.");
    }

    let default_config = r#"# Nemo Configuration
# Generated by `nemo init`

[limits]
max_rounds_harden = 10
max_rounds_implement = 15

[timeouts]
implement_secs = 1800
review_secs = 900
test_secs = 1800
audit_secs = 900
revise_secs = 900
watchdog_secs = 900

[models]
implementor = "claude-opus-4"
reviewer = "gpt-5.4"
"#;

    std::fs::write(nemo_toml, default_config)?;
    println!("Created nemo.toml");
    println!("  Edit this file to configure your project settings.");

    Ok(())
}
