use anyhow::Result;
use std::path::Path;

/// Generate a nemo.toml configuration file by scanning the monorepo.
pub fn run(force: bool) -> Result<()> {
    let nemo_toml = Path::new("nemo.toml");

    if nemo_toml.exists() && !force {
        anyhow::bail!("nemo.toml already exists. Use --force to overwrite.");
    }

    // Scan for common project markers to auto-detect services
    let mut services = String::new();
    let markers = [
        ("Cargo.toml", "rust-project", "cargo test"),
        ("package.json", "node-project", "npm test"),
        ("go.mod", "go-project", "go test ./..."),
        ("pom.xml", "java-project", "mvn test"),
        ("build.gradle", "gradle-project", "gradle test"),
        ("pyproject.toml", "python-project", "pytest"),
    ];

    for (marker, name, test_cmd) in &markers {
        if Path::new(marker).exists() {
            services.push_str(&format!(
                r#"
[services.{name}]
path = "."
test = "{test_cmd}"
tags = []
"#
            ));
        }
    }

    if services.is_empty() {
        services = r#"
# [services.my-service]
# path = "src/"
# test = "cargo test"
# tags = []
"#
        .to_string();
    }

    // Detect repo name from current directory
    let repo_name = std::env::current_dir()
        .ok()
        .and_then(|p| p.file_name().map(|n| n.to_string_lossy().to_string()))
        .unwrap_or_else(|| "my-project".to_string());

    // Detect default branch from git
    let default_branch = detect_default_branch().unwrap_or_else(|| "main".to_string());

    let config = format!(
        r#"# Nemo Configuration
# Generated by `nemo init`

[repo]
name = "{repo_name}"
default_branch = "{default_branch}"

[limits]
max_rounds_harden = 10
max_rounds_implement = 15

# Per-stage K8s Job `activeDeadlineSeconds` overrides. These flow
# through to every `nemo harden` / `nemo start` / `nemo ship` run
# submitted from this repo — the CLI attaches them to the submit
# request and the server pins them on the loop record so retries and
# resumes inherit the budget. Floor enforced at 300s server-side.
[timeouts]
implement_secs = 7200
review_secs    = 3600
test_secs      = 7200
audit_secs     = 3600
revise_secs    = 3600
watchdog_secs  = 3600

[models]
implementor = "claude-opus-4"
reviewer = "gpt-5.4"
{services}"#
    );

    std::fs::write(nemo_toml, config)?;
    println!("Created nemo.toml");
    if services.contains("[services.") && !services.contains("# [services.") {
        println!("  Auto-detected project structure. Review and adjust as needed.");
    } else {
        println!("  No project markers found. Add [services.<name>] sections manually.");
    }

    // TODO(V1.5): Use control-plane/src/config/repo.rs nested service scanner
    // instead of root-only marker detection for full monorepo support.

    Ok(())
}

/// Detect the default branch from git remote HEAD.
fn detect_default_branch() -> Option<String> {
    let output = std::process::Command::new("git")
        .args(["symbolic-ref", "refs/remotes/origin/HEAD"])
        .output()
        .ok()?;
    if output.status.success() {
        let refname = String::from_utf8_lossy(&output.stdout).trim().to_string();
        refname.rsplit('/').next().map(String::from)
    } else {
        None
    }
}
